# Generated by Django 5.2.5 on 2025-09-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilado',
            name='imagen_hover',
            field=models.ImageField(blank=True, help_text='Solo para accesorios: imagen al pasar el mouse', null=True, upload_to='hilados/'),
        ),
    ]
