# Generated by Django 5.2.5 on 2025-09-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_hilado_imagen_hover'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroCrochet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='hilado',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hilado',
            name='numeros_crochet',
            field=models.ManyToManyField(blank=True, help_text='Solo para accesorios: números de crochet disponibles', to='miapp.numerocrochet'),
        ),
    ]
