# Generated by Django 5.2.5 on 2025-09-28 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_numerocrochet_hilado_stock_hilado_numeros_crochet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hilado',
            name='numeros_crochet',
        ),
        migrations.CreateModel(
            name='StockCrochet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_crochet', to='miapp.hilado')),
                ('numero_crochet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.numerocrochet')),
            ],
            options={
                'unique_together': {('accesorio', 'numero_crochet')},
            },
        ),
    ]
