# Generated by Django 5.2.5 on 2025-09-28 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_compra_detallecompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronDescargable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='patrones/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Usuarios que pueden descargar este patrón', related_name='patrones_descargables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
