# Generated by Django 5.2.5 on 2025-09-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_patrondescargable'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilado',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='numerocrochet',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
