# Generated by Django 5.2.5 on 2025-09-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_hilado_precio_numerocrochet_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrondescargable',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de portada para el patrón', null=True, upload_to='patrones/imagenes/'),
        ),
    ]
