# Generated by Django 5.2.5 on 2025-09-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_patrondescargable_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrondescargable',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
